#configure database
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb?serverTimeZone=UTC
    username: root
    password: Ujju@2211
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  multipart:
    enabled: true
    file-size-threshold: 2KB
    max-file-size: 300MB
    max-request-size: 315MB 
    
    
  
server:
  port: 8080
pass:
  app:
    jwtSecret: ujjwalSecretKey
    jwtExpirationMs: 86400000
    
  
file:
  base-dir: C:/Users/mindfire/Documents/GitHub/
  upload-dir: rentingit_backend/src/main/resources/Upload